[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "unitree_rl_lab"
version = "0.2.1"
description = "Reinforcement Learning Lab for Unitree Robots."
dependencies = [
    "isaaclab==2.3.2.post1",
    "isaacsim==5.1.0.0",
    "psutil==5.9.8",
    "argcomplete",
]
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [
    { name = "Unitree Robotics" }
]
maintainers = [
    { name = "Unitree Robotics" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux"
]
dynamic = []

[tool.setuptools]
packages = ["unitree_rl_lab"]
